version: '3.7'
# Create golang service
networks:
    golang:
        driver: bridge
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang
    container_name: golang
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - golang
    restart: on-failure
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITRD_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITRD_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITRD_DATABASE: ${MONGO_DB}
    volumes:
      - ./mongo-data:/data/db
    networks:
      - golang
    restart: on-failure